### PR TITLE
Created missing profile endpoints

### PR DESCRIPTION
**Pull request by Sh4dow8080**
- Delete order endpoint
- Update order endpoint
- Order sold endpoint (Decrease quantity by 1)

### CODE REVIEW

**Comment by Sh4dow8080** [comment]
Forgot to mention in the description, i have removed all the misc endpoints as they were returning 404 for me

**Comment by KycKyc** [comment]
@Sh4dow8080 Misc endpoints is on dev build and will be deployed in the next update.
Please return them =)

**Comment by KycKyc** [comment]
Api docs was extracted into separate public repo after i added all these endpoint a while ago

**Comment by Sh4dow8080** [comment]
Anymore changes you would like me to make before merging?

**Comment by KycKyc** [comment]
i'll finish my current tasks, will check and merge it, thanks !

**Review by lonnstyle — APPROVED** [review]
Please update the repo according to the comments

**Comment by Sh4dow8080** [comment]
I will commit the changes you requested some time this weel :relaxed:

**Comment by lonnstyle** [comment]
since the author hasn't resolve the conversations and being inactive for so long, I'm marking this PR as stale for now

**Pull request closed without merging**
